services:
  hosts:
    gateway: http://localhost:8080
    user: http://localhost:8081
    task: http://localhost:8083
    file: http://localhost:8082
    auth: http://localhost:8089
    notification: http://localhost:8084
  ports:
    gateway: 8080
    user: 8081
    task: 8083
    file: 8082
    auth: 8089
    notification: 8084

spring:
  security:
    oauth2:
      resourceserver:
        user-info-uri: ${services.hosts.auth}/internal/user-info
        jwt:
          issuer-uri: http://localhost:8089