server:
  port: ${services.ports.auth}
spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8089
  data:
    mongodb:
      uri: mongodb://localhost/demo_auth
      auto-index-creation: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${PG_URL:jdbc:postgresql://localhost:5432/hr_auth_db}
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:1012}
    hikari:
      schema: auth_schema
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: auth
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: update
  sql:
    init:
      mode: never
